from .depot import Depot
from .produit import Produit
from .fournisseur import Fournisseur
from .client import Client
from .bon_commande import BonCommande
from .stock import Stock
from .mouvement import Mouvement
from .facture_vente import FactureVente
from .incident import Incident